### PR TITLE
Add link to reference docs in README

### PR DESCRIPTION
**Pull request by Leo-Ryu**
Hi there!

My name is Leo, a CS student at Brown building an automated platform for editable codebase documentation.

I generated documentation for this repository and placed a link in the README. Please feel free to try it out and let me know what you think!

### CODE REVIEW

**Comment by jrj-d** [comment]
Hey Leo-Ryu, thanks for your interest and contribution! Can you tell us more about contour.so? 
We have not yet decided what tool we'll use for code documentation, and contour.so was not on our radar so I'm interested to learn more.

**Comment by Leo-Ryu** [comment]
Sure thing!

contour.so is a codebase documentation platform that:

1) has a modern markdown editor to allow people to quickly and easily create new documents/user guides
2) is similar to readthedocs/sphinx in that reads through the codebase and builds/hosts linkable pages describing classes and functions, as well as their usages in the codebase. However unlike readthedocs/sphinx, contour doesn't require any configuration to get up and running
3) contour.so tracks github repositories so that every build has the latest code

Let me know if you do/don't find this useful or if there is any additional functionality you'd like to have and I will implement :)

**Comment by Leo-Ryu** [comment]
To follow up, if there's **any** feature you'd like for your documentation, I will tailor the platform to your needs-- just let me know!

**Comment by jrj-d** [comment]
Hey @Leo-Ryu , sorry for not answering earlier. We're not interested at the moment but we'll keep your service in mind should we have this need.

**Pull request closed without merging**
